######################################################################
# Automatically generated by qmake (2.01a) lun. ao�t 31 09:58:51 2009
######################################################################

CONFIG += debug
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += xml

# Input
RESOURCES += assistant.qrc
HEADERS += win.h
SOURCES += main.cpp win.cpp
