######################################################################
# Automatically generated by qmake (2.01a) sam. juil. 11 14:11:59 2009
######################################################################

CONFIG += debug
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += xml

# Input
HEADERS += parser.h
SOURCES += main.cpp parser.cpp

target.path=/usr/bin

INSTALLS += target
