/*
 * parser.cpp
 * This file is part of Logram
 *
 * Copyright (C) 2009 - Denis Steckelmacher <steckdenis@logram-project.org>
 *
 * Logram is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * Logram is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Logram; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA  02110-1301  USA
 */

#include "parser.h"

Parser::Parser(const QString &in) : QDomDocument()
{
    mfile = new QFile(in);
    setContent(mfile);
    snum = 0;
}

Parser::~Parser()
{
    delete mfile;
}

QString Parser::parse(bool &success, const QString &prevUrl, const QString &prevTitle, const QString &nextUrl, const QString &nextTitle, const QString &topUrl, const QString &topTitle)
{
    QDomElement el = documentElement();
    QString title = el.attribute("title");
    QString copyright = el.attribute("copyright", "Logram's docmentation team");
    
    //Template de début
    QString rs = "<html>\n"
                 "    <head>\n"
                 "        <title>" + title + "</title>\n"
                 "        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf8\">\n"
                 "\n"
                 "        <link rel=\"stylesheet\" href=\"logram-doc.css\" type=\"text/css\">\n"
                 "    </head>\n"
                 "    <body>\n"
                 "        <div id=\"header\">\n"
                 "            <div id=\"header_left\">\n"
                 "                <div id=\"header_right\">Logram</div>\n"
                 "            </div>\n"
                 "        </div>\n"
                 "\n"
                 "        <div id=\"body\">\n"
                 + parseElement(documentElement()) +
                 "        </div>\n"
                 "\n"
                 "        <div id=\"footer\">\n";
    
    //Liens de navigation
    bool isNav = false;
    if (!prevUrl.isNull())
    {
        rs +=    "            <a class=\"button_left\" href=\"" + prevUrl + "\">&lt; " + prevTitle + "</a>\n";
        isNav = true;
    }
    if (!topUrl.isNull())
    {
        rs +=    "            <a class=\"button_middle\" href=\"" + topUrl + "\">" + topTitle + "</a>\n";
        isNav = true;
    }
    if (!nextUrl.isNull())
    {
        rs +=    "            <a class=\"button_right\" href=\"" + nextUrl + "\">" + nextTitle + " &gt;</a>\n";
        isNav = true;
    }
    
    if (isNav) rs += "<br />\n";
    
    rs +=        "            Copyright (C) " + copyright + " CC-By-Sa<br />\n"
                 "            This document was generated by Logram doc2html on " + QDateTime::currentDateTime().toString() + "\n"
                 "        </div>\n"
                 "    </body>\n"
                 "</html>";
    
    return rs;
}

QString Parser::parseElement(const QDomNode &node)
{
    QString rs;
    
    //Explorer les sous-éléments de cet élément
    QDomNode nd = node.firstChild();
    
    while (!nd.isNull())
    {
        //Concaténer le contenu de l'élément en fonction de son type
        if (nd.isText())
        {
            QString ct = nd.nodeValue().trimmed();
            
            if (nd.nodeValue().startsWith(' '))
            {
                ct = " " + ct;
            }
            
            if (nd.nodeValue().endsWith(' '))
            {
                ct = ct + " ";
            }
            
            //Replacer les acronymes
            foreach (const QString &acr, acronyms.keys())
            {
                ct.replace(acr, "<acronym label=\"" + acronyms.value(acr) + "\">" + acr + "</acronym>");
            }
            
            rs += ct;
        }
        else if (nd.isElement())
        {
            //C'est un élément tout simple
            QDomElement el = nd.toElement();
            
            if (el.tagName() == "para")
            {
                QString align = el.attribute("align", "left");
                
                rs += "<p style=\"text-align: " + align + ";\">" + parseElement(nd) + "</p>\n";
            }
            else if (el.tagName() == "bold")
            {
                rs += "<span class=\"bold\">" + parseElement(nd) + "</span>\n";
            }
            else if (el.tagName() == "italic")
            {
                rs += "<span class=\"italic\">" + parseElement(nd) + "</span>\n";
            }
            else if (el.tagName() == "underline")
            {
                rs += "<span class=\"underline\">" + parseElement(nd) + "</span>\n";
            }
            else if (el.tagName() == "path")
            {
                rs += "<span class=\"path\">" + parseElement(nd) + "</span>\n";
            }
            else if (el.tagName() == "menu")
            {
                rs += "<span class=\"menu\">" + parseElement(nd).replace('>', "&bull;").replace('/', "&bull;") + "</span>\n";
            }
            else if (el.tagName() == "key")
            {
                rs += "<span class=\"key\">" + parseElement(nd) + "</span>\n";
            }
            else if (el.tagName() == "e")
            {
                rs += "<span class=\"emphasis\">" + parseElement(nd) + "</span>\n";
            }
            else if (el.tagName() == "app")
            {
                rs += "<span class=\"appname\">" + parseElement(nd) + "</span>\n";
            }
            else if (el.tagName() == "image")
            {
                QString url = el.attribute("url");
                QString desc = el.attribute("description");
                
                rs += "<img src=\"" + url + "\" alt=\"\" machin=\"" + desc + "\" />\n"; //TODO: Machin = ?
            }
            else if (el.tagName() == "button")
            {
                QString type = el.attribute("type", "normal");
                QString to = el.attribute("to");
                QString label = el.attribute("label");
                
                if (!to.contains('/') && to != "#")
                {
                    //Juste un nom de page, ajouter .html à la fin
                    to += ".html";
                }
                
                rs += "<a class=\"button_" + type + "\" href=\"" + to + "\">" + label + "</a>\n";
            }
            else if (el.tagName() == "break")
            {
                rs += "<br />\n";
            }
            else if (el.tagName() == "link")
            {
                QString to = el.attribute("to");
                
                if (!to.contains('/') && to != "#")
                {
                    //Juste un nom de page, ajouter .html à la fin
                    to += ".html";
                }
                
                rs += "<a href=\"" + to + "\">" + parseElement(nd) + "</a>\n";
            }
            else if (el.tagName() == "error")
            {
                rs += "<div class=\"error\">" + parseElement(nd) + "</div>\n";
            }
            else if (el.tagName() == "warning")
            {
                rs += "<div class=\"warning\">" + parseElement(nd) + "</div>\n";
            }
            else if (el.tagName() == "question")
            {
                rs += "<div class=\"question\">" + parseElement(nd) + "</div>\n";
            }
            else if (el.tagName() == "info")
            {
                rs += "<div class=\"info\">" + parseElement(nd) + "</div>\n";
            }
            else if (el.tagName() == "list")
            {
                rs += "<ul>" + parseElement(nd) + "</ul>\n";
            }
            else if (el.tagName() == "element")
            {
                rs += "<li>" + parseElement(nd) + "</li>\n";
            }
            else if (el.tagName() == "acronym")
            {
                QString name = el.attribute("name");
                QString label = el.attribute("label");
                
                acronyms.insert(name, label);
            }
            else if (el.tagName() == "title")
            {
                rs += "<h1>" + parseElement(nd) + "</h1>\n";
            }
            else if (el.tagName() == "subtitle")
            {
                snum++;
                rs += "<h2><span>" + QString::number(snum) + "</span> " + parseElement(nd) + "</h2>\n";
            }
            else
            {
                qFatal("Unknown tag %s", qPrintable(el.tagName()));
            }
        }
        
        nd = nd.nextSibling();
    }
    
    return rs;
}