######################################################################
# Automatically generated by qmake (2.01a) sam. sept. 5 13:56:44 2009
######################################################################

CONFIG += debug
TEMPLATE = app
TARGET = 
DEPENDPATH += .
QT -= gui
LIBS += -llgrpkg

# Input
HEADERS += app.h
SOURCES += cache.cpp main.cpp app.cpp util.cpp package.cpp communication.cpp string.cpp source.cpp

target.path = /usr/bin

INSTALLS += target