######################################################################
# Automatically generated by qmake (2.01a) mer. juil. 15 16:01:49 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lkhtml

# Input
SOURCES += main.cpp
HEADERS += myclass.h

target.path=/usr/bin

INSTALLS += target
