######################################################################
# Automatically generated by qmake (2.01a) mer. avr. 14 15:17:41 2010
######################################################################

CONFIG += debug
TEMPLATE = app
TARGET = buildserver
DEPENDPATH += .
RESOURCES = buildserver.qrc
QT += sql xml
LIBS += -llgrpkg -larchive
QMAKE_CXXFLAGS += -D_FILE_OFFSET_BITS=64 -Wall

# Input
HEADERS += app.h worker.h thread.h
SOURCES += app.cpp main.cpp worker.cpp thread.cpp
