#!/bin/bash

# $1 = action (install, remove, purge)
# $2 = nom du paquet
# $3 = version du paquet
# $4 = chemin du .tlz (absolu, dans le cache)
# $5 = Préfixe d'installation

#################
#### Fonctions d'aide pour le pkgbuild
#################

message()
{
    echo "MESSAGE#$1"
}

#################
#### Fonctions d'installation/suppression
#################

depack()
{
    # $1 = nom du paquet
    # $2 = version du paquet
    # $3 = chemin du .tlz
    # $4 = préfixe d'installation

    # Créer le dossier temporaire de l'extraction
    tempdir=$4/var/cache/lgrpkg/temp/$1_$2
    mkdir -p $tempdir

    # Se placer dedans et y extraire l'archive
    pwd=$PWD
    
    cd $tempdir
    tar --lzma -xf $3

    cd $pwd
}

inst()
{
    # $1 = nom du paquet
    # $2 = version du paquet
    # $3 = chemin du .tlz
    # $4 = préfixe d'installation

    tempdir=$4/var/cache/lgrpkg/temp/$1_$2
    pwd=$PWD
    cd $tempdir

    # Trouver la liste des fichiers à copier, et les copier
    find -not -type d | grep -v __LOGRAM > /tmp/$1$2_files

    cat /tmp/$1$2_files | xargs "-d\n" cp -a --parents -t "$4"

    # Enregistrer la liste des fichiers dans la base de donnée (format texte)
    dbdir=$4/var/cache/lgrpkg/db/pkgs/$1_$2
    mkdir -p $dbdir
    
    mv /tmp/$1$2_files $dbdir/files.list

    # Enregistrer le pkgbuild dans cette même base de donnée
    cp __LOGRAM/pkgbuild.sh $dbdir

    # Revenir au dossier
    cd $pwd

    # Supprimer le dossier temporaire
    rm -rf $tempdir
}

remove()
{
    # $1 = nom du paquet
    # $2 = version du paquet
    # $3 = préfixe d'installation

    /bin/echo "remove"
}

purge()
{
    # $1 = nom du paquet
    # $2 = version du paquet
    # $3 = préfixe d'installation
    
    /bin/echo "remove"
}

case "$1" in
    install)
        depack $2 $3 $4 $5
        
        source /var/cache/lgrpkg/temp/$2_$3/__LOGRAM/pkgbuild.sh

        preinst $2 $3 $5
        inst $2 $3 $4 $5
        postinst $2 $3 $5
        ;;
    remove)
        remove $2 $3 $5
        ;;
    purge)
        purge $2 $3 $5
        ;;
esac

exit 0