#!/bin/bash

# $1 = action (install, remove, purge)
# $2 = nom du paquet
# $3 = version du paquet
# $4 = chemin du .tlz (absolu, dans le cache)
# $5 = Préfixe d'installation

#################
#### Fonctions d'aide pour le pkgbuild
#################

communicate()
{
    # Nom de la communication
    str="[[>>|$1"
    
    # Paramètres
    shift
    
    while [ ${#1} -ne 0 ]; do
        str="$str|$1|$2"
        
        shift 2
    done
    
    str="$str|<<]]"
    /bin/echo "$str" >&2
    
    # Attendre une réponse, et l'échoer, ce qui permet d'attendre que l'utilisateur ait lu le message,
    # répondu à une question (et dans ce cas la réponse nous arrive), etc
    read rs
    echo "$rs"
}

#################
#### Fonctions d'installation/suppression
#################

depack()
{
    # $1 = nom du paquet
    # $2 = version du paquet
    # $3 = chemin du .tlz
    # $4 = préfixe d'installation

    # Créer le dossier temporaire de l'extraction
    tempdir=$4/var/cache/lgrpkg/temp/$1_$2
    mkdir -p $tempdir || exit 1

    # Se placer dedans et y extraire l'archive
    pwd=$PWD
    
    cd $tempdir || exit 1
    tar --lzma -xf $3 || exit 1

    cd $pwd || exit 1
}

inst()
{
    # $1 = nom du paquet
    # $2 = version du paquet
    # $3 = chemin du .tlz
    # $4 = préfixe d'installation

    tempdir=$4/var/cache/lgrpkg/temp/$1_$2
    pwd=$PWD
    cd $tempdir || exit 1

    # Trouver la liste des fichiers à copier, et les copier
    find -not -type d | grep -v __LOGRAM > /tmp/$1$2_files || exit 1

    cat /tmp/$1$2_files | xargs "-d\n" cp -a --parents -t "$4" || exit 1

    # Enregistrer la liste des fichiers dans la base de donnée (format texte)
    dbdir=$4/var/cache/lgrpkg/db/pkgs/$1_$2
    mkdir -p $dbdir || exit 1
    
    mv /tmp/$1$2_files $dbdir/files.list || exit 1

    # Enregistrer le pkgbuild dans cette même base de donnée
    cp __LOGRAM/pkgbuild.sh $dbdir || exit 1
    cp __LOGRAM/metadata.xml $dbdir || exit 1

    # Revenir au dossier
    cd $pwd || exit 1

    # Supprimer le dossier temporaire
    rm -rf $tempdir || exit 1
}

remove()
{
    # $1 = nom du paquet
    # $2 = version du paquet
    # $3 = préfixe d'installation

    /bin/echo "remove"
}

purge()
{
    # $1 = nom du paquet
    # $2 = version du paquet
    # $3 = préfixe d'installation
    
    /bin/echo "remove"
}

case "$1" in
    install)
        depack $2 $3 $4 $5 || exit 1
        
        source $5/var/cache/lgrpkg/temp/$2_$3/__LOGRAM/pkgbuild.sh || exit 1

        preinst $2 $3 $5 || exit 1
        inst $2 $3 $4 $5 || exit 1
        postinst $2 $3 $5 || exit 1
        ;;
    remove)
        remove $2 $3 $5 || exit 1
        ;;
    purge)
        purge $2 $3 $5 || exit 1
        ;;
esac

exit 0