######################################################################
# Automatically generated by qmake (2.01a) mer. juil. 8 19:09:52 2009
######################################################################

CONFIG += debug
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += xml

# Input
HEADERS += window.h
SOURCES += main.cpp window.cpp

target.path=/usr/bin

INSTALLS += target
