#!/bin/bash

# Importer le contenu d'un .tlz dans la dépôt, phase de préparation
file=$1
name=$(echo $file | cut -d '.' -f 1)

echo ">> Importing $name..."

# 1. Décompresser
mkdir tmp
cd tmp

tar --lzma -xf ../$file

cd ..

# 2. Copier le Control
cp tmp/__LOGRAM/control $name.control

# 3. Copier les fichiers de traduction
cp tmp/__LOGRAM/$name.* ./

# 4. Supprimer le tmp
rm -rf tmp