#!/bin/bash

filename=$1
name=$(echo $filename | cut -d '~' -f 1)

# Créer l'architecture de dossiers
if [ "${name:0:3}" = "lib" ]; then
    d=${name:0:4}
else
    d=${name:0:1}
fi

dir=pool/$d/$name
mkdir -p $dir

# Copier le fichier .tlz dedans
cp incoming/$filename $dir

# Copier le fichier .control également
cp incoming/$name.control $dir

# Générer la liste des fichiers
tar --lzma --list -f incoming/$filename > $dir/$filename.files
