#!/bin/bash

action=$1

# Script de gestion d'un dépôt
source conf/config.sh

usage()
{
    echo "Logram Repository Manager v0.1"
    echo
    echo "Usage: $0 action [parameters]"
    echo "    - action     : One of the following actions"
    echo "    - parameters : Parameters"
    echo
    echo "Actions:"
    echo "    - prepare <package> : Prepare a package for importing"
    echo "    - include <package> : Include a package in the distribution specified in its .control"
    echo "    - tellv4            : Ask the v4 to import the packages in its database"
    echo "    - export            : Export the distributions"
    echo "    - process           : Process all the packages in incoming"
}

prepare()
{
    # $1 = chemin d'accès d'un .tlz
    file=$1
    name=$(basename $file | cut -d '~' -f 1)

    echo ">> Importing $name..."

    # 1. Obtenir les tailles
    dlsize=$(ls $file -l | cut -d ' ' -f 5)

    # 2. Décompresser
    lzma -dc $file > uncompressed.tar
    insize=$(ls uncompressed.tar -l | cut -d ' ' -f 5)

    # 3. Extraire les fichiers
    mkdir tmp
    cd tmp

    tar -xf ../uncompressed.tar

    cd ..

    # 4. Copier le Control
    bname=$(basename $file .tlz)
    cp tmp/__LOGRAM/control $INCOMING/$bname.control

    echo "DownloadSize=$dlsize" >> $INCOMING/$bname.control
    echo "InstallSize=$insize" >> $INCOMING/$bname.control

    # 5. Copier les descriptions courtes pour utilisation plus tard
    for f in tmp/__LOGRAM/descriptions.*; do
        lang=$(echo $f | cut -d '.' -f 2)
        short_title=$(cat $f | grep -e "^$name:")
        
        echo "$short_title" > $INCOMING/$name.desc.$lang
        
        # Récupérer le titre et la description longue pour ce paquet et cette langue
        xml sel -T -B -t -m "//package[@name='$name']/title/$lang" -v . -n tmp/__LOGRAM/metadata.xml > $INCOMING/$name.$lang
        echo >> $INCOMING/$name.$lang
        echo "$short_title" | cut -d ':' -f 2- >> $INCOMING/$name.$lang
        echo >> $INCOMING/$name.$lang
        
        # Description longue
        found="false"
        index="0"
        line=""
        
        xml sel -T -B -t -m "//package[@name='$name']/description/$lang" -v . -n tmp/__LOGRAM/metadata.xml | sed -e 's/^ *//g' \
        | (while read l; do
            if [ $found = "true" ]; then
                echo "$line" >> $INCOMING/$name.$lang
            fi
            
            # Si la ligne n'est pas vide, ou alors qu'on est au centre du fichier, l'ajouter
            if [ ${#l} -ne 0 -o $found = "true" ]; then
                found="true"
                
                line="$l"
            fi
        done)
        
        if [ ${#line} -ne 0 ]; then
            echo "$line" >> $INCOMING/$name.$lang
        fi
        
        if [ $found = "false" ]; then
            echo >> $INCOMING/$name.$lang
        fi
    done

    # 6. Copier les métadonnées
    cp tmp/__LOGRAM/metadata.xml $INCOMING/$name.metadata.xml

    # 7. Supprimer le tmp
    rm -rf tmp
    rm -f uncompressed.tar
}

include()
{
    # $1 = chemin d'accès d'un .tlz
    filename=$1
    bname=$(basename $filename)
    name=$(echo $bname | cut -d '~' -f 1)
    arch=$(echo | awk "{ c = split(\"$bname\", a, \".\"); print a[c-1] }")

    echo ">> Including $name ($arch)..."

    # Créer l'architecture de dossiers
    if [ "${name:0:3}" = "lib" ]; then
        d=${name:0:4}
    else
        d=${name:0:1}
    fi

    dir=$POOL/$d/$name
    metadir=$METADATA/$d/$name
    mkdir -p $dir
    mkdir -p $metadir

    # Copier le fichier .tlz dedans
    cp $filename $dir

    # Copier le fichier .control également
    if [[ ! $filename == *.src.tlz ]]; then
        # Le fichier control contient [Binary], le remplacer la le nom du paquet
        firstline="true"
        content=""
        while read line; do
            if [ $firstline = "true" ]; then
                firstline="false"
                continue
            fi

            # Rajouter la ligne dans content (elle contient le \n)
            content="$content$line\n"

            # Si on a la distribution, la prendre
            if [ ${line:0:12} = "Distribution" ]; then
                distrib=${line:13}
            fi

            # Si on a la version, la prendre
            if [ ${line:0:7} = "Version" ]; then
                version=${line:8}
            fi
        done < $INCOMING/$(basename $filename .tlz).control

        # Écrire dans dists/<distrib>/<arch>/parts/<d>/<name>.control
        cdir=$DISTS/$distrib/$arch/parts/$d
        mkdir -p $cdir
        
        # Copier et adapter tous les fichiers langue du paquet (<name>.desc.*)
        cp $INCOMING/$name.desc.* $cdir
        
        # Copier les métadonnées
        cat $INCOMING/$name.metadata.xml | lzma > $metadir/$name~$version.metadata.xml.lzma
        
        # Fichier .control
        echo "[$name]" > $cdir/$name.control
        echo "Arch=$arch" >> $cdir/$name.control
        echo "PackageHash=$(cd $(dirname $POOL) && sha1sum -b $filename | cut -d ' ' -f 1)" >> $cdir/$name.control
        echo "MetadataHash=$(cd $(dirname $METADATA) && sha1sum -b $metadir/$name~$version.metadata.xml.lzma | cut -d ' ' -f 1)" >> $cdir/$name.control
        echo -e "$content" >> $cdir/$name.control
    fi

    # Générer la liste des fichiers
    tar --lzma --list -f $filename > $dir/$bname.files
}

tellv4()
{
    rs=$(wget -q -O - $V4URL)

    if [ "$rs" != "Done" ]; then
        echo "v4 failed !"
        exit 1
    fi
}

exp()
{
    # Explorer les distributions
    for distro in $DISTS/*
    do
        dname=$(basename $distro)
        
        # Explorer les architectures
        for arch in $distro/*
        do
            aname=$(basename $arch)
            
            echo -n ">> $dname ($aname)..."

            # Bêtement concaténer le contenu des fichiers de parts
            find $arch/parts -name '*.control' -exec cat {} \; | lzma > $arch/packages.lzma
            
            # Signer ce fichier
            (cd $arch && gpg --yes --local-user $SIGN_USER --detach-sign packages.lzma)

            # Générer les fichiers de langue
            for lang in $LANGS
            do
                find $arch/parts -name "*.$lang" -exec cat {} \; | lzma > $arch/translate.$lang.lzma
                
                # Signer ce fichier
                (cd $arch && gpg --yes --local-user $SIGN_USER --detach-sign translate.$lang.lzma)
            done

            echo " done"
        done
    done
}

process()
{
    # Explore les fichiers .tlz dans incoming et les importe
    for fl in `ls $INCOMING/*.tlz`
    do
        if [ ! -f "$fl" ]; then
            break
        fi

        # Préparer le paquet (seulement un binaire)
        if [[ ! $fl == *.src.tlz ]]; then
            prepare $fl
        fi

        # Importer le paquet
        include $fl
    done

    # Demande à la v4 de recharger sa liste
    tellv4
}

case $action in
    help)
        usage
        ;;
    prepare)
        prepare $2
        ;;
    include)
        include $2
        ;;
    process)
        process
        ;;
    tellv4)
        tellv4
        ;;
    export)
        exp
        ;;
    *)
        usage
        ;;
esac